---
- name: install prerequisit packages
  apt:
    name:
    - apt-transport-https
    - ca-certificates
    - curl
    - gnupg-agent
    - software-properties-common
    - python3-pip
    update_cache: yes
- name: add docker apt key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
- name: add docker apt repository
  apt_repository:
    repo: 'deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable'
    state: present
    filename: docker
- name: install docker
  apt:
    name:
    - docker-ce
    - docker-ce-cli
    - containerd.io
- name: install python packages for ansible
  pip:
    name:
    - docker
    - jsondiff
    - pyyaml
